src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shelves.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shelves/urls.py
from django.urls import path, include
from . import views

app_name = 'shelves'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/<str:pk>', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:pk>/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('recommend_user/', views.RecommendUserView.as_view(), name='recommend_user'),
    path('book_search/', views.BookSearchView.as_view(), name='book_search'),
    path('book/<str:pk>', views.BookDetailView.as_view(), name='book_detail'),
]

src/shelves/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.conf import settings
from annoying.fields import AutoOneToOneField

class RecommendUser(models.Model):
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    critics = models.TextField('評価一覧')
    post_cnt_log = models.FloatField('投稿数の対数')

class Book(models.Model):
    book_id = models.CharField('ID',max_length=256, primary_key=True, unique=True)
    title = models.CharField('タイトル',max_length=256)
    cover_url = models.CharField('画像URL',max_length=256,blank=True)

    def __str__(self):
        return self.title

class Post(models.Model):
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    item = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
    )

    title = models.CharField('記事タイトル',max_length=256, blank=True)
    comment = models.TextField('コメント', blank=True)
    rating = models.FloatField('評価',default=2.5)
    public = models.BooleanField('公開', default=False)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)

    def __str__(self):
        return self.title

class Profile(models.Model):
    username = AutoOneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True
    )
    sentence = models.TextField('プロフィール文',max_length=300, blank=True)

    def __str__(self):
        return self.username

class AppUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):

        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)

        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, False, False, **extra_fields)
    
    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True, **extra_fields)

class AppUser(AbstractBaseUser, PermissionsMixin):

    username=models.CharField(_('username'), max_length=20, unique=True, primary_key=True, db_index=True)
    email = models.EmailField(_('email address'))
    displayname = models.CharField('表示名', max_length=20)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    objects = AppUserManager()

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

src/shelves/forms.py
from django import forms
from .models import AppUser, Post, Profile, Book
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class SignUpForm(UserCreationForm):
    class Meta:
        model = AppUser
        fields = ("username","email", "displayname")
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("sentence",)

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","rating","comment")

        widgets = {
            "rating": forms.NumberInput(
                attrs={
                    "type":"range",
                    "step":"0.1",
                    "min":"0.0",
                    "max":"5.0",
                    "v-model":"score",
                }
            )
        }
class PostDeleteForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ()

class BookCreateForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ("title","book_id","cover_url")

        widgets = {
            "title": forms.HiddenInput(
                attrs={
                    "v-model":"book.volumeInfo.title",
                }
            ),
            "book_id": forms.HiddenInput(
                attrs={
                    "v-model":"book.volumeInfo.industryIdentifiers[0].identifier",
                }
            ),
            "cover_url": forms.HiddenInput(
                attrs={
                    "v-if":"book.volumeInfo.imageLinks !== $0",
                    "v-model":"book.volumeInfo.imageLinks.thumbnail",
                }
            ),
        }

src/shelves/views.py
from django.views import generic
from django.db.models import Case, When
from django.db import transaction
from .models import Post, AppUser, Profile, RecommendUser, Book
from django.urls import path, reverse_lazy
from django.shortcuts import resolve_url
from django.http import HttpResponseRedirect
from django.contrib.auth import views, mixins
from .forms import LoginForm, SignUpForm, ProfileUpdateForm, PostUpdateForm, PostDeleteForm, BookCreateForm
from .api.GoogleBooksAPI import get_thumbnail_url
from .recommendations.rating import recommend_user
import numpy as np
import json

class IndexView(generic.ListView):
    template_name = 'shelves/index.html'
    context_object_name = 'posted_list'

    def get_queryset(self):
        return Post.objects.filter(public=True).order_by('-created_at')

class RecommendUserView(generic.ListView):
    template_name = 'shelves/recommend_user.html'
    context_object_name = 'recommend_user_list'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return recommend_user(self.request.user)
        else:
            return []

class LoginView(views.LoginView):
    form_class = LoginForm
    template_name = 'shelves/login.html'

class LogoutView(views.LogoutView, mixins.LoginRequiredMixin):
    template_name = 'shelves/logout.html'

class SignUpView(generic.CreateView):
    form_class = SignUpForm
    template_name = 'shelves/signup.html'
    success_url = reverse_lazy('shelves:login')

class ProfileView(generic.DetailView):
    template_name = 'shelves/profile.html'
    model = AppUser

class ProfileUpdateView(mixins.UserPassesTestMixin, generic.UpdateView):
    raise_exception = False

    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'shelves/profile_update.html'

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

    def get_success_url(self):
        return resolve_url('shelves:profile', pk=self.kwargs['pk'])

class PostDetailView(generic.DetailView):
    template_name = 'shelves/post_detail.html'
    model = Post

class PostUpdateView(mixins.UserPassesTestMixin, generic.UpdateView):
    raise_exception = False

    model = Post
    form_class = PostUpdateForm
    template_name = 'shelves/post_update.html'

    def test_func(self):
        created_user = Post.objects.get(id=self.kwargs['pk']).created_by.username
        user = self.request.user
        return user.pk == created_user or user.is_superuser

    def get_success_url(self):
        return resolve_url('shelves:post_detail', pk=self.kwargs['pk'])

    def form_valid(self, form):
        form.instance.public = True
        return super().form_valid(form)

class PostDeleteView(mixins.UserPassesTestMixin, generic.DeleteView):
    model = Post
    form_class = PostDeleteForm
    success_url = reverse_lazy('shelves:index')
    template_name = 'shelves/post_delete.html'

    def test_func(self):
        created_user = Post.objects.get(id=self.kwargs['pk']).created_by.username
        user = self.request.user
        return user.pk == created_user or user.is_superuser

class BookSearchView(generic.CreateView):
    model = Book
    template_name = 'shelves/book_search.html'
    form_class = BookCreateForm

    def get_success_url(self):
        return resolve_url('shelves:post_update', pk=self.new_post.pk)

    def form_valid(self, form):
        self.object = form.save()

        self.new_post = Post(item=self.object, created_by=self.request.user, title=self.object.title, rating=2.5)
        self.new_post.save()

        return super().form_valid(form)

    def form_invalid(self, form):
        book = Book.objects.get(pk=form.instance.book_id)

        self.new_post = Post(item=book, created_by=self.request.user, title=book.title, rating=2.5)
        self.new_post.save()

        return HttpResponseRedirect(self.get_success_url())

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'shelves/book_detail.html'

src/shelves/templates/shelves/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'shelves/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}Shelves{% endblock %}</title>
</head>
<body>
  <div class="container">
    <div class="text-center h1 p-4">
      Shelves
    </div>
    <ul class="nav nav-tabs justify-content-center">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'shelves:index' %}">タイムライン</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'shelves:book_search' %}">投稿</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shelves:recommend_user' %}">おすすめユーザー</a>
      </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">アカウント</a>
            <div class="dropdown-menu">
              {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'shelves:profile' user.username %}">プロフィール</a>
                <a class="dropdown-item" href="{% url 'shelves:profile_update' user.username %}">プロフィールの編集</a>
                <a class="dropdown-item" href="{% url 'shelves:logout' %}">ログアウト</a>
              {% else %}
                <a class="dropdown-item" href="{% url 'shelves:login' %}">ログイン</a>
                <a class="dropdown-item" href="{% url 'shelves:signup' %}">サインアップ</a>
              {% endif %}
            </div>
          </li>
    </ul>
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'shelves/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'shelves/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

src/shelves/templates/shelves/book_detail.html
{% extends "shelves/base.html" %}
{% load staticfiles %}
{% load humanize %}

{% block content %}
<div class="border border-light rounded mt-5 text-center">
    <div class="h2 m-3">{{ object.title }}</p>
    <div class="m-4"><img src="{{ object.cover_url }}" ></div>
</div>

<div class="h4 p-5 text-center">投稿一覧</div>
<div class="d-flex flex-wrap justify-content-center p-4">
    {% for post in object.post_set.all %}
        <div class="border border-light rounded m-1 p-4">
            <div class="h5 mb-2">{{ post.created_by.displayname }}</div>
            <div class="h4 text-warning mb-3">{{ post.rating }}</div>
            <div><a href="{% url 'shelves:post_detail' post.id%}">詳しく読む</a></div>
        </div>
    {% endfor %}
</div>

{% endblock %}

src/shelves/templates/shelves/book_search.html
{% extends "shelves/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}

<div id=app>
    <form class="border border-light rounded p-4">
        <div class="form-group">
            <label>キーワード（タイトル、著者など）：</label>
            <input type="text" class="form-control" v-model="name"><br>
            <input type="button" v-on:click="getUrl()" name="" value="検索" class="btn btn-primary float-right"><br>
        </div>
    </form>
    <div>
        {% if not user.is_authenticated %}
        投稿には<a href="{% url 'shelves:login' %}">ログイン</a>が必要です
        {% endif %}
    </div>
    <div v-for="book in books">
        <div class="border border-light rounded p-5" v-if="book.volumeInfo.industryIdentifiers !== $0">
            <div class="p-2 h5">[[ book.volumeInfo.title ]]</div>
            <div class="row align-items-center">
                <div class="col-sm-2 text-center" v-if="book.volumeInfo.imageLinks !== $0"><img :src="book.volumeInfo.imageLinks.thumbnail"></div>
                <div class="col-sm-2 text-center" v-else>No Image</div>
                <div class="col-sm-8 text-wrap"><br>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item border-light">
                            <div>著者：</div>
                            <ul class="list-group-horizontal">
                                <li v-for="author in book.volumeInfo.authors" class="list-group-item border-light">[[ author ]]</li>
                            </ul>
                        </li>
                        <li class="list-group-item border-light">出版社：[[ book.volumeInfo.publisher ]]</li>
                        <li class="list-group-item border-light">出版日：[[ book.volumeInfo.publishedDate ]]</li>
                    </ul>
                </div>
            </div>
            {% if user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary float-right" type="submit">記事を書く</button>
            </form>
            {% endif %}
        </div>
    </div>

</div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'shelves/js/book_search.js' %}"></script>
{% endblock %}

src/shelves/templates/shelves/index.html
{% extends "shelves/base.html" %}
{% load staticfiles%}
{% load humanize %}

{% block content %}

<div class="text-right p-1">
    {% if not user.is_authenticated %}
        <p><a href="{% url 'shelves:login' %}">ログイン</a>または<a href="{% url 'shelves:signup' %}">サインアップ</a></p>
    {% endif %}
</div>

{% for post in posted_list %}
<div class="p-2">
    <div class="border border-light rounded p-4">
        <div class="h4">{{ post.title | linebreaksbr }}</div>
        <p>{{ post.created_by.displayname }}<a href="{% url 'shelves:profile' post.created_by.username %}">@{{ post.created_by.username }}</a> {{ post.created_at | naturaltime}}</p>
        <div class="row">
            <div class="col-sm-3"><a href="{% url 'shelves:book_detail' post.item.pk %}"><img src="{{ post.item.cover_url }}" /></a></div>
            <div class="col-sm-8">
                評価：<div class="mb-4 text-warning h4">{{ post.rating }}</div>
                <div class="text-truncate h-50">{{ post.comment | linebreaksbr }}</div>
            </div>
        </div>
        <div class="text-right"><a href="{% url 'shelves:post_detail' post.id%}">詳しく読む</a></div>
    </div>
</div>
{% empty %}
<div class="p-4">投稿がありません</div>
{% endfor %}

{% endblock %}

src/shelves/templates/shelves/login.html
{% extends "shelves/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="p-4">

<form method="post">

{% csrf_token %}
{{ form|crispy }}

<button class="btn btn-primary float-right" type="submit">ログイン</button>
</form>

</div>

{% endblock %}

src/shelves/templates/shelves/logout.html
{% extends "shelves/base.html" %}

{% block content %}

ログアウトしました

<div><a href="{% url 'shelves:index' %}">ホーム</a></div>

{% endblock %}

src/shelves/templates/shelves/post_create.html
{% extends "shelves/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}

<form method="post">
{% csrf_token %}
<div>
    {{ form.title|as_crispy_field}}
</div>
<div>
    {{ form.comment|as_crispy_field }}
</div>
<div id="rating" class="container">
    {{ form.rating.label_tag}}
    <p class="h4">[[ score ]]</p>
    {{ form.rating }}
</div><br>

<button class="btn btn-primary" type="submit">投稿</button>
</form>

{% endblock %}

{% block extra_js %}
<script src="{% static 'shelves/js/post_create.js' %}"></script>
{% endblock %}

src/shelves/templates/shelves/post_delete.html
{% extends "shelves/base.html" %}
{% load staticfiles%}

{% block content %}
<div class="border border-light rounded mt-5 text-center">
<div class="row">
    <div class="col-12">
    <p>{{ object }} を削除していいですか?</p>
    <form method=post>
        <button class="btn btn-danger">削除する</button>
        {% csrf_token %}
    </form>
    </div>
</div>
</div>
{% endblock %}

src/shelves/templates/shelves/post_detail.html
{% extends "shelves/base.html" %}
{% load staticfiles %}
{% load humanize %}

{% block content %}

<div class="border border-light rounded mt-5 text-center">
    <div class="h2 m-3">{{ object.title }}</div>
    <div class="m-4">{{ object.created_by.displayname }}<a href="{% url 'shelves:profile' post.created_by.username %}">@{{ object.created_by.username }}</a></div>
    <div class="m-2">{{ object.created_at.year }} 年 {{ object.created_at.month }} 月 {{ object.created_at.day }} 日 {{ object.created_at.hour }} 時 {{ object.created_at.minute }} 分</div>
    <div class="m-4"><a href="{% url 'shelves:book_detail' object.item.pk %}"><img src="{{ object.item.cover_url }}" ></a></div>
    <div class="p-4 text-wrap text-left">{{ object.comment | linebreaksbr}}</div>
    {% if user.username == object.created_by.username %}
        <div><a href="{% url 'shelves:post_update' object.id %}">編集</a></div>
        <div><a href="{% url 'shelves:post_delete' object.id %}">削除</a></div>
    {% endif %}
</div>

{% endblock %}

src/shelves/templates/shelves/post_update.html
{% extends "shelves/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}

<div class="p-4">

<form method="post">
{% csrf_token %}
<div>
{{ form.title|as_crispy_field }}
{{ form.comment|as_crispy_field }}
</div>
<div id="rating" class="container">
    {{ form.rating.label_tag}}
    <div class="h4 text-warning">[[ score ]]</div>
    {{ form.rating }}
</div><br>

<button class="btn btn-primary float-right" type="submit">投稿</button>
</form>

</div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'shelves/js/post_update.js' %}"></script>
{% endblock %}

src/shelves/templates/shelves/profile.html
{% extends "shelves/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="border border-light rounded mt-4 p-4">
    <div class="h5">{{ object.displayname }}</div>
    <div class="p-4">{{ object.profile.sentence}}</div>
</div>

<div class="d-flex flex-wrap justify-content-center">
    {% for post in object.post_set.all %}
        {% if post.public == True %}
            <div class="p-3"><a href="{% url 'shelves:post_detail' post.id%}"><img src="{{ post.item.cover_url }}" height="150"/></a></div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}

src/shelves/templates/shelves/profile_update.html
{% extends "shelves/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="p-4">

<form method="post">

{% csrf_token %}
{{ form|crispy }}

<button class="btn btn-primary float-right" type="submit">更新</button>
</form>

</div>

{% endblock %}

src/shelves/templates/shelves/recommend_user.html
{% extends "shelves/base.html" %}
{% load staticfiles%}
{% load humanize %}

{% block content %}

{% for rec_user in recommend_user_list %}

<div class="border border-light rounded p-5">
    <div class="text-center">{{ rec_user.displayname }}<a href="{% url 'shelves:profile' rec_user.username %}">@{{ rec_user.username }}</a></div>
    <div class="d-flex flex-wrap justify-content-center">
        {% for post in rec_user.post_set.all %}
            {% if post.public == True %}
                <div class="p-3"><a href="{% url 'shelves:post_detail' post.id%}"><img src="{{ post.item.cover_url }}" height="100"/></a></div>
            {% endif %}
        {% endfor %}
    </div>
</div>

{% empty %}
<p class="p-4">おすすめユーザーがいません</p>
{% endfor %}

{% endblock %}

src/shelves/templates/shelves/signup.html
{% extends "shelves/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
<button class="btn btn-primary" type="submit">サインアップ</button>
</form>
{% endblock %}